0.4.3 (MuJoCo 3.3.5)
=====================
- Removed unnecessary header files (smaller crate size).

0.4.2 (MuJoCo 3.3.5)
=====================
- Renamed env vars: ``MUJOCO_DYNAMIC_LINK_LIB`` → ``MUJOCO_DYNAMIC_LINK_DIR``,
  ``MUJOCO_STATIC_LINK_LIB`` → ``MUJOCO_STATIC_LINK_DIR``.

0.4.1 (MuJoCo 3.3.5)
=====================
- Fixed event handling.

0.4.0 (MuJoCo 3.3.5)
=====================
- Renamed package to ``mujoco-rs``.

